SELECT 
    SUM(A.SCORE) AS SCORE,
    A.EMP_NO,
    B.EMP_NAME,
    B.POSITION,
    B.EMAIL
FROM 
    HR_GRADE A JOIN HR_EMPLOYEES B
    ON A.EMP_NO = B.EMP_NO
WHERE
    A.YEAR = 2022
GROUP BY
    A.EMP_NO
ORDER BY
    SUM(A.SCORE) DESC
LIMIT 1